[package]
name = "valida-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
valida-rs = { git = "https://github.com/lita-xyz/valida-rs.git", branch = "main" }
serde = "1.0"
k256 = { version = "0.13", features = ["serde"] }
serde_json = "1.0.122"